import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";
// import Image from "next/image";
// import moment from "moment";
import Link from "next/link";
import { request, gql } from "graphql-request";

const graphqlAPI =
  "https://api-ap-northeast-1.graphcms.com/v2/ckwsga7el479z01z10tjr979t/master";
// "https://api-eu-central-1.graphcms.com/v2/cku56f92114s901yz0ce9ah3f/master";

const testing = async () => {
  // const query = gql`
  //   query MyQuery2 {
  //     postsConnection {
  //       edges {
  //         node {
  //           author {
  //             name
  //           }
  //         }
  //       }
  //     }
  //   }
  // `;

  const query = gql`
    query findSlug {
      posts {
        slug
      }
    }
  `;

  // const query = gql`
  //   query MyQuery {
  //     postsConnection {
  //       edges {
  //         node {
  //           author {
  //             bio
  //             name
  //             id
  //             photo {
  //               url
  //             }
  //           }
  //           createdAt
  //           slug
  //           title
  //           excerpt
  //           featuredImage {
  //             url
  //           }
  //           categories {
  //             name
  //             slug
  //           }
  //         }
  //       }
  //     }
  //   }
  // `;

  const result = await request(graphqlAPI, query);
  const data = result.posts;
  console.log(data);
  // const results = result.postsConnection.edges;

  return {
    props: {
      data,
    },
  };
};

// testing();

const Home = ({ data }) => {
  // testing();
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
