import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";
// import Image from "next/image";
// import moment from "moment";
import Link from "next/link";
import { gql, GraphQLClient } from "graphql-request";

// const graphqlAPI =
//   "https://api-ap-northeast-1.graphcms.com/v2/ckwsga7el479z01z10tjr979t/master";
// // "https://api-eu-central-1.graphcms.com/v2/cku56f92114s901yz0ce9ah3f/master";

export const getStaticProps = async () => {
  const url =
    "https://api-ap-northeast-1.graphcms.com/v2/ckwsga7el479z01z10tjr979t/master";

  const graphQLClient = new GraphQLClient(url);

  const query = gql`
    query findSlug {
      posts {
        slug
      }
    }
  `;

  const result = await graphQLClient.request(query);
  const data = result.posts;
  console.log(data);
  // const results = result.postsConnection.edges;

  return {
    props: {
      data,
    },
  };
};

// export async function getStaticProps() {
//   const posts = await testing();

//   return {
//     props: { posts },
//   };
// }

// testing();

const Home = ({ data }) => {
  // const getData = testing().then((data) => console.log(data));
  // const data = await testing();
  console.log(data);
  // console.log(getData.data);
  // testing();
  // console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* {posts.map((items, index) => (
          <h1 key={index}>{items.slug}</h1>
        ))} */}
      </main>
    </div>
  );
};

export default Home;

//https://www.youtube.com/watch?v=u1ovHJXkPBY&ab_channel=CodewithAniaKub%C3%B3w
